### ISSUE TITLE
How to use this file in php frameworks

### ISSUE THREAD

**Issue by NICANDIAS** [yocto/yoclib-wbxml-php#1]
Please i am new to WBXML files and i am not sure where to put the codes (Encrypt and Decrypt) as shown in your readme.md file.

Kindly make some clarifications about where to use those codes.

Warm regards
Ekun Abdulhakeem

**Comment by ben221199** [comment]
For encoding, use the following code.
```php
use YOCLIB\WBXML\CodePages\ExchangeActiveSync;
use YOCLIB\WBXML\WBXMLEncoder;
use YOCLIB\WBXML\WBXMLException;

$xml = '<FolderSync/>';

$codePages = ExchangeActiveSync::getCodePages();

$encoder = new WBXMLEncoder($codePages);

try{
	$binary = $encoder->encode($xml);
}catch(WBXMLException $e){
	//TODO
}
```

In this code `$xml` is the XML you want to encode, `$codePages` are the codepages you encode `$xml` with, `$encoder` is the encoder loaded with your codepages, `$binary` is the encoded output. In this case, Exchange ActiveSync is used as example codepages. WBXML is used in this protocol.

For decoding, use this code:
```php
use YOCLIB\WBXML\CodePages\ExchangeActiveSync;
use YOCLIB\WBXML\WBXMLDecoder;
use YOCLIB\WBXML\WBXMLException;

$binary = "\x03\x01\x6a\x00\x00\xff\xff";

$codePages = ExchangeActiveSync::getCodePages();

$decoder = new WBXMLDecoder($codePages);

try{
	$xml = $decoder->decode($binary);
}catch(WBXMLException $e){
	//TODO
}
```
In here `$binary` is binary you want to decode, `$codePages` is the same as above, `$decoder` is the decoder loaded with your codepages, `$xml` is the decoded output. Also in this case, Exchange ActiveSync is used as example codepages.

Note that the library isn't 100% working, because some slight details are missing, but you should be able to use it.

**Comment by NICANDIAS** [comment]
Thank you very much, this really helped me solve my problem.

Warm Regards
Ekun Abdulhakeem

**Comment by ben221199** [comment]
No problem :)
